@serve_url=http://localhost:8082
@admin_username=admin
@admin_password=admin

####### Session
###
GET {{serve_url}}/api/server
Accept: application/json

###
PUT {{serve_url}}/api/server
Content-Type: application/json
Accept: application/json
Authorization: Basic {{admin_username}}:{{admin_password}}

{
  "id": 1,
  "registration": false,
  "readonly": false,
  "deviceReadonly": false,
  "limitCommands": false,
  "map": "googleRoad",
  "bingKey": null,
  "mapUrl": null,
  "poiLayer": null,
  "latitude": 14.720471,
  "longitude": -17.4587,
  "zoom": 17,
  "twelveHourFormat": false,
  "version": "5.8",
  "forceSettings": false,
  "coordinateFormat": null,
  "openIdEnabled": false,
  "openIdForce": false,
  "attributes": {
    "timezone": "Africa/Dakar"
  }
}

####### create admin user
POST {{serve_url}}/api/users
Content-Type: application/json
Accept: application/json
Authorization: Basic {{admin_username}}:{{admin_password}}

{
  "id": 0,
  "name": "Aristide",
  "email": "mendoo.aristide@gmail.com",
  "phone": "+221773675573",
  "readonly": false,
  "administrator": false,
  "map": "googleRoad",
  "latitude": 14.720471,
  "longitude": -17.4587,
  "zoom": 17,
  "password": "passer12345",
  "twelveHourFormat": false,
  "coordinateFormat": null,
  "disabled": false,
  "expirationTime": null,
  "deviceLimit": -1,
  "userLimit": 0,
  "deviceReadonly": false,
  "limitCommands": false,
  "fixedEmail": false,
  "poiLayer": null,
  "attributes": {
    "activeMapStyles": ",googleRoad,osm",
    "timezone": "Africa/Dakar",
    "mapFollow": true,
    "mapGeofences": true,
    "mapCluster": true,
    "mapOnSelect": true,
    "positionItems": "speed,address,totalDistance,course,batteryLevel,fuelConsumption,fuel,battery",
    "mapLiveRoutes": "all",
    "mapDirection": "all"
  }
}

### 
GET {{serve_url}}/api/users/2
Content-Type: application/json
Accept: application/json
Authorization: Basic {{admin_username}}:{{admin_password}}



